services:
    giftcards.encryption.listener.abstract_encrypted_listener:
        class: Giftcards\Encryption\Doctrine\EventListener\EncryptedListener
        arguments:
            - '@giftcards.encryption.doctrine.field_encryptor'
            - '@giftcards.encryption.listener.encrypt_listener.driver'
        abstract: true
          
    giftcards.encryption.listener.encrypt_listener.driver:
        class: Giftcards\Encryption\Doctrine\Configuration\Metadata\Driver\AnnotationDriver
        public: false
        arguments:
            - '@annotation_reader'
            
    giftcards.encryption.doctrine.field_encryptor:
        class: Giftcards\Encryption\Doctrine\FieldEncryptor
        arguments:
            - '@giftcards.encryption.encryptor'