services: 
    omni.encryption.encryption_manager:
        class: Omni\EncryptionBundle\Manager\EncryptionManager
        arguments: ["@logger","%OMNI_ENCRYPTION_STRING%"]
  
    creditcard.listener:
        class: Omni\EncryptionBundle\Listener\AesEncryption
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: postLoad }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: postPersist }
        arguments: ["@omni.encryption.encryption_manager"]