services: 

    omni.encryption.key_source:
        alias: omni.encryption.key_source.chain
        
    omni.encryption.cipher_text_store.registry:
        class: Omni\Encryption\CipherText\StoreRegistry
        
    omni.encryption.cipher.registry:
        class: Omni\Encryption\Cipher\CipherRegistry
        
    omni.encryption.profile.registry:
        class: Omni\Encryption\Profile\ProfileRegistry
        
    omni.encryption.key_source.chain:
        class: Omni\Encryption\Key\ContainerAwareChainSource
        arguments:
            - @service_container
        
    omni.encryption.encryptor.mysql_aes_encryptor:
        class: Omni\Encryption\Cipher\MysqlAes
        tags:
            - { name: omni.encryption.encryptor }
        
    omni.encryption.encryptor.no_op_encryptor:
        class: Omni\Encryption\Cipher\NoOp
        tags:
            - { name: omni.encryption.encryptor }
     
    omni.encryption.encryptor:
        class: Omni\Encryption\Encryptor
        arguments:
            - @omni.encryption.cipher.registry
            - @omni.encryption.key_source
            - @omni.encryption.profile.registry
        
    omni.encryption.command.migrate_key:
        class: Omni\Encryption\Command\MigrateKeyCommand
        arguments:
            - @omni.encryption.cipher_text_store.registry
            - @omni.encryption.encryptor
        tags:
            - { name: console.command }