services: 

    giftcards.encryption.key_source:
        alias: giftcards.encryption.key_source.chain
        
    giftcards.encryption.cipher_text_serializer_deserializer:
        alias: giftcards.encryption.cipher_text_serializer_deserializer.chain
        
    giftcards.encryption.cipher_text_rotator.registry:
        class: Giftcards\Encryption\CipherText\Rotator\ContainerAwareRotatorRegistry
        arguments:
            - '@service_container'
        
    giftcards.encryption.cipher.registry:
        class: Giftcards\Encryption\Cipher\ContainerAwareCipherRegistry
        arguments:
            - '@service_container'
        
    giftcards.encryption.profile.registry:
        class: Giftcards\Encryption\Profile\ProfileRegistry
        
    giftcards.encryption.key_source.chain:
        class: Giftcards\Encryption\Key\ContainerAwareChainSource
        arguments:
            - '@service_container'
        
    giftcards.encryption.cipher.mysql_aes:
        class: Giftcards\Encryption\Cipher\MysqlAes
        tags:
            - { name: giftcards.encryption.cipher, alias: mysql_aes }
        
    giftcards.encryption.cipher.no_op:
        class: Giftcards\Encryption\Cipher\NoOp
        tags:
            - { name: giftcards.encryption.cipher, alias: no_op }
    
    giftcards.encryption.cipher_text_serializer_deserializer.chain:
        class: Giftcards\Encryption\CipherText\Serializer\ContainerAwareChainSerializerDeserializer
        arguments:
            - '@service_container'
     
    giftcards.encryption.encryptor:
        class: Giftcards\Encryption\Encryptor
        arguments:
            - '@giftcards.encryption.cipher.registry'
            - '@giftcards.encryption.key_source'
            - '@giftcards.encryption.profile.registry'
            - '@giftcards.encryption.cipher_text_serializer_deserializer'
            - default_profile
        
    giftcards.encryption.command.rotate_encryption_profile:
        class: Giftcards\Encryption\Command\RotateEncryptionProfileCommand
        arguments:
            - '@giftcards.encryption.cipher_text_rotator.registry'
            - '@giftcards.encryption.encryptor'
        tags:
            - { name: console.command }

    giftcards.encryption.rotator:
        class: Giftcards\Encryption\CipherText\Rotator\Rotator
        arguments:
            - '@giftcards.encryption.encryptor'
            - '@giftcards.encryption.store_registry' #TODO: Create this service

    giftcards.encryption.command.rotate_store:
        class: Giftcards\Encryption\Command\RotateStoreCommand
        arguments:
            - '@giftcards.encryption.rotator'
            - '@giftcards.encryption.rotator.tracker' #TODO: Create this service

    giftcards.encryption.command.rotate_range:
        class: Giftcards\Encryption\Command\RotateRangeInStoreCommand
        arguments:
            - '@giftcards.encryption.rotator'