services: 

    omni.encryption.key_source:
        alias: omni.encryption.key_source.chain
        
    omni.encryption.cipher_text_serializer:
        alias: omni.encryption.cipher_text_serializer.chain
        
    omni.encryption.cipher_text_deserializer:
        alias: omni.encryption.cipher_text_deserializer.chain
        
    omni.encryption.cipher_text_rotator.registry:
        class: Omni\Encryption\CipherText\Rotator\ContainerAwareRotatorRegistry
        arguments:
            - @service_container
        
    omni.encryption.cipher.registry:
        class: Omni\Encryption\Cipher\ContainerAwareCipherRegistry
        arguments:
            - @service_container
        
    omni.encryption.profile.registry:
        class: Omni\Encryption\Profile\ProfileRegistry
        
    omni.encryption.key_source.chain:
        class: Omni\Encryption\Key\ContainerAwareChainSource
        arguments:
            - @service_container
        
    omni.encryption.cipher.mysql_aes:
        class: Omni\Encryption\Cipher\MysqlAes
        tags:
            - { name: omni.encryption.cipher, alias: mysql_aes }
        
    omni.encryption.cipher.no_op:
        class: Omni\Encryption\Cipher\NoOp
        tags:
            - { name: omni.encryption.cipher, alias: no_op }
    
    omni.encryption.cipher_text_serializer.chain:
        class: Omni\Encryption\CipherText\Serializer\ContainerAwareChainSerializer
        arguments:
            - @service_container
    
    omni.encryption.cipher_text_deserializer.chain:
        class: Omni\Encryption\CipherText\Serializer\ContainerAwareChainDeserializer
        arguments:
            - @service_container
     
    omni.encryption.encryptor:
        class: Omni\Encryption\Encryptor
        arguments:
            - @omni.encryption.cipher.registry
            - @omni.encryption.key_source
            - @omni.encryption.profile.registry
            - @omni.encryption.cipher_text_serializer
            - @omni.encryption.cipher_text_deserializer
            - default_profile
        
    omni.encryption.command.rotate_encryption_profile:
        class: Omni\Encryption\Command\RotateEncryptionProfileCommand
        arguments:
            - @omni.encryption.cipher_text_rotator.registry
            - @omni.encryption.encryptor
        tags:
            - { name: console.command }