services: 
    omni.encryption.encryption_manager:
        class: Omni\EncryptionBundle\Manager\EncryptionManager
        arguments: ["@logger","@doctrine","%OMNI_ENCRYPTION_STRING%"]
  
    creditcard.listener:
        class: Omni\EncryptionBundle\Listener\AesEncryption
        tags:
            - { name: doctrine.event_listener, event: preUpdate, method: preUpdate }
            - { name: doctrine.event_listener, event: prePersist, method: prePersist }
            - { name: doctrine.event_listener, event: postLoad, method: postLoad }
            - { name: doctrine.event_listener, event: postUpdate, method: postSave }
            - { name: doctrine.event_listener, event: postPersist, method: postSave }
        arguments: ["@omni.encryption.encryption_manager"]